---
# cobbler-web pulls in cobbler
cobbler_package: cobbler-web
cobbler_service: cobblerd
httpd_service: httpd
cobbler_extra_packages:
  - git
  - syslinux
  - pykickstart
  - fence-agents-all
  - nmap
  - python-pip
  - python2-crypto
