---
# Restart networking
- name: restart networking
  service:
    name: network
    state: restarted

# Restart fail2ban
- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

# Reload fail2ban
- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded
